### ISSUE TITLE
Adding combination lock does not allow personal code

### ISSUE THREAD

**Issue by GolovaRaoul** [AirwavesMan/Over9000-Panthera#23]
Adding combination lock does not allow personal code

When you add lock to door, it shows you the code screen for you to enter own code.
If you enter own code and press "unlock", you will get error "Unlock allready in progress" and you will get assigned a random code to your door

**Comment by AirwavesMan** [comment]
Change door code will be removed with Update 1.58. The problem itself is still persistent but since we removed the change code for doors we do not have to fix it.
